import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import type { NextPage } from "next";
import { ChatBubbleLeftRightIcon, SparklesIcon } from "@heroicons/react/24/outline";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Proof of Prompt</title>
        <meta name="description" content="Created with 🏗 scaffold-eth" />
      </Head>

      <div className="flex items-center flex-col flex-grow pt-10">
        <div className="px-5">
          <h1 className="text-center mb-8">
            <span className="block text-2xl mb-2">Welcome to</span>
            <span className="block text-4xl font-bold">Proof of Prompt (PoP)</span>
          </h1>
          <Image
            className={"mx-auto"}
            src={"/poppop.gif"}
            alt={"Gif of a clip of the character magnitude saying Pop Pop from the acclaimed TV show Community"}
            width={480}
            height={270}
          />
          <p className="text-center text-lg">An experiment with AI and inmutable sources of &#34;truth&#34;.</p>
          <p className="text-center text-lg">
            This app is basically a clone of Chat GPT (
            <Link href={"https://platform.openai.com/"} target="_blank">
              you will need an Open AI API Key to use it
            </Link>
            ), with an option to store the whole conversation on-chain, FOREVER!
          </p>
          <p className="text-center text-lg">
            Now you can prove to everyone that the latest trendy response from Chat GPT was generated by your prompts!
          </p>
        </div>

        <div className="flex-grow bg-base-300 w-full mt-16 px-8 py-12">
          <div className="flex justify-center items-center gap-12 flex-col sm:flex-row">
            <div className="flex flex-col bg-base-100 px-10 py-10 text-center items-center max-w-xs rounded-3xl">
              <ChatBubbleLeftRightIcon className="h-8 w-8 fill-secondary" />
              <p>
                Chat with your OpenAI model of preference{" "}
                <Link href="/chat" passHref className="link">
                  HERE
                </Link>{" "}
                <br />
                You will be able to choose between GPT-3.5 Turbo and GPT-4 (like the cool kids, if your API Key allows
                it).
              </p>
            </div>
            <div className="flex flex-col bg-base-100 px-10 py-10 text-center items-center max-w-xs rounded-3xl">
              <SparklesIcon className="h-8 w-8 fill-secondary" />
              <p>
                If you choose to, a copy of your whole chat session, plus a signed messaged, will be stored in IPFS, and
                for a modest fee, you can mint a collectible!
                <br />
                Check your{" "}
                <Link href="/collection" passHref className="link">
                  Collection
                </Link>{" "}
                of prompts, stored as NFTs!
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
